### ISSUE TITLE
Can not build an Extension on Mac when pysnmp library is used

### ISSUE THREAD

**Issue by lkoniecki** [dynatrace-extensions/dynatrace-extensions-vscode#146]
**Describe the bug**
I have the following setup.py:

```
from setuptools import setup

setup(name="xyz",
      version="0.0.12",
      description="xyz",
      author="lukasz.koniecki",
      packages=["xyz"],
      python_requires=">=3.10",
      include_package_data=True,
      install_requires=["dt-extensions-sdk", "pysnmp", "pycryptodomex"],
      extras_require={"dev": ["dt-extensions-sdk[cli]"]},
      )
```

The Extension does not build on Mac because of the following error:

```
Could not find a version that satisfies the requirement pycryptodomex (from xyz) (from versions: none)\nERROR: No matching distribution found for pycryptodomex
```

The command used to build it by the VSCode Ext. 

```
python@3.11/bin/python3.11 -m pip download -d extension/lib --only-binary=:all: --platform linux_x86_64
```

pip downloads a pycryptodomex but in the `pycryptodomex-3.19.0-cp35-abi3-macosx_10_9_universal2.whl` version not the `pycryptodomex-3.19.0-cp35-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.why` which is required to build the package for Linux.

I can build the Extension manually using the following command:

```
dt-sdk build --extra-platform manylinux_2_17_x86_64 xyz
```

**Steps to reproduce**
1. Include pysnmp into your Extension 2.0 python project
2. Invoke the "Dynatrace extensions: Build" command

**Expected behavior**
I should be able to develop and build an Extension on Mac.

**Comment by radu-stefan-dt** [comment]
Thank you for raising this issue.

The root cause is [how we build the python wheels](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/blob/main/src/commandPalette/buildExtension.ts#L167-L173)

So that the extension functions on both Linux and Windows platforms, we will build wheels using the `linux_x86_64` and `win_amd64` platforms as extras in the pip command.

However, some packages out there (e.g. pycryptodomex, grpcio, etc.) have adopted PEP600 style of referencing linux platform in a format like yours - `manylinux_2_17_x86_64`

We cannot guess this in advance. So, to allow you to override the platforms, I will add a settings parameter for the workspace that allows you to specify your platforms.

**Comment by radu-stefan-dt** [comment]
Setting will support a list of strings, each being a platform to build for. Will look like this in the UI:

![image](https://github.com/dynatrace-extensions/dynatrace-extensions-vscode/assets/16157796/282c1137-e871-4914-b157-3e3bd5820d0e)

This should be used per workspace, as it will overwrite our default logic.

Example usage inside `.vscode/settings.json` at workspace level:

```json
{
    "dynatraceExtensions.pythonExtraPlatforms": [
        "manylinux_2_17_x86_64",
    ]
}
```

These platforms will be added as options to flag `-e` for the pip download command that's internally used to fetch wheels.
