### ISSUE TITLE
Switch to direct extension file upload

### ISSUE THREAD

**Issue by lugowskii** [dynatrace-extensions/dynatrace-extensions-vscode#84]
The goal is to switch to direct upload for all POST calls to /api/v2/extensions. Currently extension file is sent using multipart/form-data content type, which was identified to be problematic. As an API consumer you're asked to change POST /v2/extensions request body content type to application/octet-stream.
It's not urgent. Please contact me directly if you encounter any issue with implementation.
DT reference: EXT-3708

**Comment by radu-stefan-dt** [comment]
Marking as backlog.
`application/octet-stream` introduced in 1.262, unsupported before. Both content types will be supported for next 6 months or so.

Copilot will be patched later once most customer base is at minimum 1.262 to avoid breaks or the additional effort of falling back to `form-data` in case `octet-stream` is not supported (since we don't  know the cluster version in advance).
